### ISSUE TITLE
存在语法错误

### ISSUE THREAD

**Issue by RonanTay** [wdfe/weweb#12]
C:\Users>weweb
C:\Users\creux\AppData\Roaming\npm\node_modules\weweb-cli\bin\weweb:218
  let execBuild = async function (err, out) {
                        ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

**Comment by IOriens** [comment]
You have to install Node.js above version 7.6.0, sorry for not mentioning it in our README.
