### ISSUE TITLE
运行报错 ： weweb-cli/bin/weweb:218

### ISSUE THREAD

**Issue by DreamboyA** [wdfe/weweb#14]
执行：weweb ./ShareLoverBak

报错:
<pre>
<code>
/usr/local/lib/node_modules/weweb-cli/bin/weweb:218
  let execBuild = async function (err, out) {
                        ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
</code>
</pre>

**Comment by DreamboyA** [comment]
【已解决】将node版本更新到最新版即可
