### ISSUE TITLE
Error parsing statement => this <= : Unknown Type: ThisExpression

### ISSUE THREAD

**Issue by gogobody** [wdfe/weweb#8]
遇到如下错误
`Using wxss-transpiler to transpile wxss:
Using wxml-compiler to transpile wxml:
发生了未知错误
Error parsing statement => this <= : Unknown Type: ThisExpression
    at walk (C:\Users\JavaScript\AppData\Roaming\npm\node_modules\weweb-cli\node_modules\wxml-transpiler\build.js:1:9655)
    at walk (C:\Users\JavaScript\AppData\Roaming\npm\node_modules\weweb-cli\node_modules\wxml-transpiler\build.js:1:7916)
    at walk (C:\Users\JavaScript\AppData\Roaming\npm\node_modules\weweb-cli\node_modules\wxml-transpiler\build.js:1:7856)
    at walk (C:\Users\JavaScript\AppData\Roaming\npm\node_modules\weweb-cli\node_modules\wxml-transpiler\build.js:1:7720)
    at walkExp (C:\Users\JavaScript\AppData\Roaming\npm\node_modules\weweb-cli\node_modules\wxml-transpiler\build.js:1:9764)
    at parseExp (C:\Users\JavaScript\AppData\Roaming\npm\node_modules\weweb-cli\node_modules\wxml-transpiler\build.js:1:9960)
    at parseText (C:\Users\JavaScript\AppData\Roaming\npm\node_modules\weweb-cli\node_modules\wxml-transpiler\build.js:1:7416)
    at pushProp (C:\Users\JavaScript\AppData\Roaming\npm\node_modules\weweb-cli\node_modules\wxml-transpiler\build.js:1:23531)
    at processFor (C:\Users\JavaScript\AppData\Roaming\npm\node_modules\weweb-cli\node_modules\wxml-transpiler\build.js:1:20916)
    at Object.start (C:\Users\JavaScript\AppData\Roaming\npm\node_modules\weweb-cli\node_modules\wxml-transpiler\build.js:1:18584)`

**Comment by IOriens** [comment]
等下我们会发新版，可以具体定位是那一个文件编译出了错误。

目前您可以使用 `DFT_CMP=true` 环境变量来切换至微信的编译器，或者是检查一下是否是在 for 循环中使用了错误的[语法](https://mp.weixin.qq.com/debug/wxadoc/dev/framework/view/wxml/list.html)。

**Comment by IOriens** [comment]
该问题应该已经解决了，您可以使用`npm install weweb-cli -g`命令更新脚手架，然后再次尝试。

该问题是因为上一版本不支持 this 语法，现已支持。
