### ISSUE TITLE
Error: Cannot find module 'koa-better-body'

### ISSUE THREAD

**Issue by caepek** [wdfe/weweb#9]
localhost:~ xiaoxiao$ weweb /Users/xiaoxiao/Documents/GIGOA
/Users/xiaoxiao/Documents/GIGOA
文件将生成到:
/Users/xiaoxiao/wewebTmp/dist
Using wxss-transpiler to transpile wxss: 
Using wxml-compiler to transpile wxml:
Export login.js Success!
Export selectpeople.js Success!
Export mainpage.js Success!
Export selectdepartment.js Success!
Export operatingprogress.js Success!
Export index.js Success!
Export newcome.js Success!
Export index.js Success!
Export index.js Success!
Export index.js Success!
发生了未知错误
Error: Cannot find module 'koa-better-body'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/weweb-cli/lib/router.js:12:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
Export index.html Success!
Export app-service.js Success!
Export app.css Success!

**Comment by caepek** [comment]
localhost:~ xiaoxiao$ npm -version
4.5.0

**Comment by IOriens** [comment]
已解决，您可以使用`npm install weweb-cli -g`命令更新脚手架，然后再次尝试。

该问题是因为`koa-better-body`模块误放在`devdependency`中了。
